version: '3.5'

networks:
  gateway: {}

volumes:
  om30_bundle:
  om30_postgresql:

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    command: foreman start -f Procfile.dev
    depends_on:
      - postgres
      - mailcatcher
    environment:
      - BINDING=0.0.0.0
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=postgres
      - DOMAIN=http://localhost
      - PORT=3000
      - MAILCATCHER_HOST=mailcatcher
      - MAILCATCHER_PORT=1025
    networks:
      - gateway
    volumes:
      - ".:/rails"
      - om30_bundle:/usr/local/bundle

  postgres:
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    #   - PGDATA=/pgtmpfs
    # tmpfs:
    #   - /pgtmpfs
    image: postgres:16.2-alpine
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 2s
      retries: 10
    logging:
      driver: none
    networks:
      - gateway
    mem_limit: 256m
    ports:
      - "5432:5432"
    volumes:
      - om30_postgresql:/var/lib/postgresql/data

  mailcatcher:
    image: 'jonathanccalixto/mailcatcher:latest'
    logging:
      driver: none
    networks:
      - gateway
    ports:
      - "1080:1080"
      - "1025:1025"
    restart: on-failure
